name: CI - Semantic Seg - Training Pipeline

on:
  push:
    branches:
      - main
      
  pull_request:      

jobs:
  ci-seg:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2.4.2      
        
    - name: 'Install required Python packages'
      
      run: |
        pip install -r requirements.txt
#     

    - name: 'Compile TFX Training Pipeline'
      if: steps.training-pipeline-change.outputs.src == 'true'    
      working-directory: 'build'
      run: |
        tfx pipeline compile \
          --pipeline-path trainer.py \
          --engine vertex
          
    - name: 'Create TFX Training Pipeline'
      if: steps.training-pipeline-change.outputs.src == 'true'    
      working-directory: 'build'
      run: |
        tfx pipeline create \
          --pipeline-path trainer.py \
          --engine vertex
      
